# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

defaults:
  -
    scope: 
      type: posts
    values:
      permalink: /:path/:title:output_ext


# Site languages
lang: en-US

# Available languages
languages:
  - pt: "pt-BR"
  - en: "en-US"

# Site title
title: "Gabriel Schaidhauer"

# A description of your site for meta tag, search engine results.
description: "This is a personal blog where I can put my ideas and share with anyone interested"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://ogabriel.com"

# Favicon
favicon: images/favicon.ico

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "G-15Y20JGRVJ"

# Site navigation - each item must have a title and a url.
navigation:
  - text: home
    url: /
  - text: about
    url: about
  - text: tags
    url: tags

# The shortname for your Disqus site to enable comments.
disqus: ogabriel-com

# Colors
accent_color: '#9DC88D'

# Site footer
footer:
  has_social: true

# http://jekyllrb.com/docs/pagination/
paginate_multiple:
- paginate: 3
  paginate_path: '/en/page:num/'
  sub_dir: '/en'
- paginate: 3
  paginate_path: '/pt/page:num/'
  sub_dir: '/pt'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
